services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - db
    networks:
      - app-network

  backend:
    build: .
    command: >
      sh -c "
      until pg_isready -h db -p 5432; do
      echo 'Esperando a que la base de datos esté lista...';
      sleep 1;
      done &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
    - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SETTINGS_MODULE=ft_transcendence_backend.settings
      - DJANGO_DEBUG=True
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    networks:
      - app-network


volumes:
  prometheus_data:
  postgres_data:
  

networks:
  app-network: 
    driver: bridge
