version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - app-network 

  backend:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
       DJANGO_SETTINGS_MODULE: ft_transcendence_backend.settings
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: .
    command: tail -f /dev/null
    volumes:
      - frontend_data:/var/lib/frontend/data
    ports:
      - "8080:8080"
    environment:
       DJANGO_SETTINGS_MODULE: ft_transcendence_frontend.settings
    depends_on:
      - backend
    networks:
      - app-network  

  grafana:
    build: ../monitoring/graphana/
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - backend
      - db
    networks:
      - app-network 

  prometheus:
    build: ../monitoring/prometheus/
    ports:
      - "3300:3300"
    volumes:
      - ../monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    depends_on:
      - backend
      - db
    networks:
      - app-network

volumes:
  grafana_data:
  postgres_data:
  prometheus_data:
  frontend_data: 

networks:
  app-network: 
    driver: bridge 
