version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  backend:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
       DJANGO_SETTINGS_MODULE: ft_transcendence_backend.settings
    depends_on:
      - db
  
  grafana:
    build: ../monitoring/graphana/
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=your_grafana_admin_password
    depends_on:
      - backend
      - db
    networks:
      - app-network

volumes:
  grafana_data:
  postgres_data:

networks:
  app-network:
    driver: bridge
