services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - app-network 

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://myuser:mypassword@db:5432/mydatabase?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - db
    networks:
      - app-network

  backend:
    build: .
    command: >
      sh -c "
      until pg_isready -h db -p 5432; do
      echo 'Esperando a que la base de datos esté lista...';
      sleep 1;
      done &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=ft_transcendence_backend.settings
      - DJANGO_DEBUG=True
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    networks:
      - app-network


  grafana:
    build: ../monitoring/grafana/
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ../monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - backend
      - db
    networks:
      - app-network 

  prometheus:
    build: ../monitoring/prometheus/
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - app-network

volumes:
  grafana_data:
  postgres_data:
  prometheus_data:
  frontend_data: 

networks:
  app-network: 
    driver: bridge
