FROM debian:bullseye

RUN apt-get -y update
RUN	apt-get install bash
RUN	apt-get install -y gpg
RUN	apt-get install -y dpkg
RUN	apt-get install -y apt-transport-https software-properties-common wget

RUN apt-get install -y adduser libfontconfig1 musl

RUN	wget https://dl.grafana.com/enterprise/release/grafana-enterprise_11.4.0_amd64.deb

RUN	dpkg -i grafana-enterprise_11.4.0_amd64.deb

RUN mkdir -p /etc/apt/keyrings/

RUN wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | tee /etc/apt/keyrings/grafana.gpg > /dev/null

RUN echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | tee -a /etc/apt/sources.list.d/grafana.list

RUN	echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com beta main" | tee -a /etc/apt/sources.list.d/grafana.list


RUN apt-get -y update


RUN apt-get install grafana-enterprise

EXPOSE 3306

