# Generated by Django 5.1.7 on 2025-03-25 12:28

from django.db import migrations, models
from django.contrib.postgres.fields import ArrayField
from django.conf import settings
from django_resized import ResizedImageField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(
                    on_delete=models.CASCADE, 
                    to=settings.AUTH_USER_MODEL,
                    related_name='profile'
                )),
                ('avatar', models.ImageField(upload_to='media/', blank=True, null=True)),                
                ('friends', ArrayField(
                    models.IntegerField(),
                    size=100,
                    blank=True,
                    default=list,
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wins', models.IntegerField(default=0, null = True)),
                ('losses', models.IntegerField(default=0, blank=True, null=True)),
                ("tournaments_won", models.IntegerField(default=0, blank=True, null=True)),
                ("is_online", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=100, null=True)),
                ('loser', models.CharField(max_length=100, null=True)),
                ('w_points', models.IntegerField(default=0)),
                ("l_points", models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('type_game', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersInTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('avatar', models.ImageField(upload_to='media/', blank=True, null=True)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('tournaments_won', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
 
